### PR TITLE
better code for handel array

### PR DESCRIPTION
**Pull request by pageye123**
Better code for handel array.

The following quote is from [JavaScript Garden](https://bonsaiden.github.io/JavaScript-Garden/#array):

> Because the for in loop enumerates all the properties that are on the prototype chain and because the only way to exclude those properties is to use hasOwnProperty, it is already up to twenty times slower than a normal for loop.

### CODE REVIEW

**Comment by muaz-khan** [comment]
DetectRTC has a separate repository:

* https://github.com/muaz-khan/DetectRTC

Please update this instead (use `grunt` command to recompile `DetectRTC.js`):

* https://github.com/muaz-khan/DetectRTC/blob/master/dev/detectDesktopOS.js#L88

**Comment by pageye123** [comment]
@muaz-khan work done and please [check it](https://github.com/muaz-khan/DetectRTC/pull/42)~

**Comment by muaz-khan** [comment]
Thanks.

**Comment by pageye123** [comment]
@muaz-khan but why don't u merger it to the RTCMultiConnection?

**Pull request closed without merging**
